### PR TITLE
Test for cors support to avoid using XDR for IE 10

### PR DESCRIPTION
**Pull request by dhcole**

### CODE REVIEW

**Comment by dhcole** [comment]
Does the same thing as #2 but uses feature detection instead of user agent parsing.

**Comment by gido** [comment]
@jaubourg What about this one ?

**Comment by jaubourg** [comment]
The thing is, it's not needed. The default xhr transport in jQuery core already catches the situation where the browser supports cors proper: https://github.com/jquery/jquery/blob/master/src/ajax/xhr.js#L36 So the xdr factory is never called in IE10.

I'll close this but thanks for participating, it's always highly appreciated when people care enough to create PRs on one of your projects :)

**Comment by gido** [comment]
Thanks for the explanation. I didn't realize that.

**Pull request closed without merging**
